# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -D ts-loader
    - run: npm install -D webpack-cli
    - run: npm install -D raw-loader
    - run: npm install -D @types/chrome
    - run: npm install -D rollup-plugin-sass
    - run: sh install.sh local
    - run: sh build.sh

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
        #name: # optional
        # Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE
        path: browser-extension/mv3/dist # optional
        # A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.
        # pattern: # optional
        # When multiple artifacts are matched, this changes the behavior of the destination directories. If true, the downloaded artifacts will be in the same directory specified by path. If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
        # merge-multiple: # optional, default is false
        # The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run. If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run.
        # github-token: # optional
        # The repository owner and the repository name joined together by "/". If github-token is specified, this is the repository that artifacts will be downloaded from.
        # repository: # optional, default is ${{ github.repository }}
        # The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from.
        # run-id: # optional, default is ${{ github.run_id }}
            
      
