name: NodeJS with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.15.0]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Build
      run: | 
        sh install.sh local
        sh build.sh

    - uses: actions/upload-artifact@v4
      with:
        name: mv3-dist
        path: browser-extension/mv3/dist/ # or path/to/artifact
        
    - uses: actions/upload-artifact@v4
      with:
        name: app-dist
        path: app/build/ # or path/to/artifact
